CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE venues (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE seats (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id  BIGINT  NOT NULL REFERENCES venues (id) ON DELETE CASCADE,
    row_num   INTEGER NOT NULL CHECK (row_num > 0),
    seat_num  INTEGER NOT NULL CHECK (seat_num > 0),
    CONSTRAINT uq_seats_position UNIQUE (venue_id, row_num, seat_num)
);

CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    type        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Сеанс = событие + площадка + время. Назвали event_sessions, чтобы не путать с HTTP/Hibernate Session
CREATE TABLE event_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT         NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    venue_id   BIGINT         NOT NULL REFERENCES venues (id),
    starts_at  TIMESTAMPTZ    NOT NULL,
    price      NUMERIC(10, 2) NOT NULL CHECK (price >= 0)
);
CREATE INDEX idx_event_sessions_event ON event_sessions (event_id);
CREATE INDEX idx_event_sessions_starts_at ON event_sessions (starts_at);

CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT         NOT NULL REFERENCES users (id),
    event_session_id  BIGINT         NOT NULL REFERENCES event_sessions (id),
    status            VARCHAR(20)    NOT NULL,
    total_price       NUMERIC(10, 2) NOT NULL CHECK (total_price >= 0),
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    expires_at        TIMESTAMPTZ    NOT NULL,
    version           BIGINT         NOT NULL DEFAULT 0
);
CREATE INDEX idx_bookings_user ON bookings (user_id);
-- для планировщика, который истекает просроченные брони
CREATE INDEX idx_bookings_pending_expires ON bookings (expires_at) WHERE status = 'PENDING';

CREATE TABLE booking_seats (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    seat_id           BIGINT         NOT NULL REFERENCES seats (id),
    event_session_id  BIGINT         NOT NULL REFERENCES event_sessions (id),
    price             NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    active            BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_booking_seat UNIQUE (booking_id, seat_id)
);
-- КЛЮЧЕВОЕ: одно место на один сеанс можно держать только в одной активной брони.
-- При отмене/истечении active ставим false, и место освобождается.
CREATE UNIQUE INDEX uq_active_seat_per_session
    ON booking_seats (event_session_id, seat_id) WHERE active;
